dist: bionic
matrix:
  include:
    - language: cpp  
      sudo: required
      compiler:
      - gcc

    - language: python
      python:
        - "3.6"
      install: # command to install dependencies
        - "pip install -r requirements.txt --user"
        - "pip install coveralls"
        - "bash make.sh"
      # command to run tests
      script: python ./test.py
      
  notifications:
    email:
      - sohrab.towfighi@mail.utoronto.ca
  after_success:
    - coveralls
