dist: bionic
matrix:
  include:
    - language: python
      python:
        - "3.6"
      install: # command to install dependencies
        - "pip install -r requirements.txt"
        - "pip install coveralls"
      # command to run tests
      script: pytest --cov=pyGOURGS -s ./test.py

    - language: cpp  
      sudo: required
      compiler:
      - gcc
        
  notifications:
    email:
      - sohrab.towfighi@mail.utoronto.ca
  after_success:
    - coveralls
